---
  ##
  # if you want to deploy this website to local kubernetes cluster:
  # 1. Make sure you have a k8s cluster setup locally
  # 2. Uncomment line 19 - 23
  # 3. Comment line 14 - 17
  ##
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - targetPort: 5000
      port: 80

  # type: NodePort
  # ports:
  #   - targetPort: 5000
  #     port: 5000
  #     nodePort: 31590

  selector:
    app: website